name: Build and Push Docker Image
on:
  push:
    tags:
      - "*"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Docker tag
        id: set_tag
        run: echo "::set-output name=tag::${{ github.ref }}"

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag_name::${{ steps.set_tag.outputs.tag | replace('refs/tags/', '') }}"

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/whatsup:${{ steps.extract_tag.outputs.tag_name }}
